name: seed-data

on:
  push:
    paths:
      - 'seed-data/**'
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
         name: Build and push Docker image
         run: |
           cd ./seed-data
           docker build -t gabykiii/seed-dataworkflows:latest .
           docker push gabykiii/seed-dataworkflows:latest
